// v2 content — from draft_v2.md, filtered for SITE layer only.
// CV/LinkedIn-specific slabs stay out of here by design.

// Anchor dates for live counters.
// IT career start: March 2013 (СаунаМастер, sysadmin).
// DevOps career start: Dec 2019 (Team Lead DevOps at Инфосистемы Джет).
window.CAREER_ANCHORS = {
  it_start:     "2013-03-01T00:00:00+03:00",
  devops_start: "2019-12-01T00:00:00+03:00",
};

window.CONTENT = {
  ru: {
    meta: {
      title: "Соловьев Максим — DevOps",
      locale: "ru_RU",
      handle: "artfaal",
      host: "solovev.dev",
      shell: "zsh",
      tz_label: "MSK",
    },
    nav: {
      mode_label: "режим",
      mode_work: "по работе",
      mode_human: "по-человечески",
      lang_label: "язык",
      cv: "скачать CV",
    },
    hero: {
      name: "Соловьев Максим",
      role: "DevOps Expert Engineer",
      prompt_lines: ["whoami", "cat ~/about.md"],
      tagline: [
        "Навожу порядок в сложных системах и автоматизирую рутину",
        "так, чтобы у людей оставались силы на жизнь.",
      ],
      sub: "Сейчас особенно копаю LLM-инструменты — те, что помогают делу, а не плодят новый зоопарк.",
      cta_primary: "написать",
      cta_secondary: "github",
      // Anchor strip directly under the name. Live counters mixed with static facts.
      anchors: [
        { k: "в IT",        mode: "live-it",     suffix: "" },
        { k: "в DevOps",    mode: "live-devops", suffix: "" },
        { k: "ВМ в проде",  mode: "static",      v: "160+" },
        { k: "инструментов",mode: "static",      v: "30+" },
        { k: "часов в LLM-зоопарке", mode: "static", v: "299" },
      ],
      portrait_hint: "наведи",
    },
    identity: {
      head: "// identity",
      title: "Кто ты в одной фразе",
      body: [
        "13 лет в IT — от единственного сисадмина в маленькой компании до DevOps-эксперта в Инфосистемы Джет. Сейчас — единственный DevOps на Jet Detective, антифрод-платформе для банков и ритейла. Отвечаю за всё: от CI/CD и мониторинга до 160+ ВМ.",
        "Прошёл путь от тимлида до эксперта — сознательно. Руководить умею, но больше ценю глубокую инженерную работу: разобраться, починить, автоматизировать, задокументировать.",
      ],
      trajectory: [
        { t: "sysadmin",    y: "2013" },
        { t: "web dev",     y: "2015" },
        { t: "devops lead", y: "2019" },
        { t: "devops expert", y: "2023", current: true },
      ],
    },
    value: {
      head: "// what i do",
      title: "Чем полезен",
      items: [
        { k: "01", t: "Привожу хаос к форме",           d: "Беру запутанные процессы и собираю их в понятную, воспроизводимую форму. Без косметики — структурно." },
        { k: "02", t: "Автоматизирую без культов",     d: "Не «потому что модно», а потому что рутина жрёт внимание. Оверинжиниринг — такой же враг, как ручной труд." },
        { k: "03", t: "Держу сложное в одиночку",       d: "Инфраструктура, дебаг, оркестрация. Работать без толпы — это навык, который тренируется годами." },
        { k: "04", t: "Отличаю инструмент от демки",   d: "Быстро вижу, где настоящая польза, а где красивая обёртка. Не даю зоопарку AI-тулов расти бесконтрольно." },
        { k: "05", t: "Мост infra ↔ AI tooling",       d: "Глубоко изучаю LLM-агентов и их применение в инженерных процессах. Помогаю сшивать инфру и современный AI без боли." },
        { k: "06", t: "Строю без «хранителя тайного знания»", d: "Документация, прозрачность, самодокументируемые системы. Чтобы не ты был точкой отказа." },
      ],
    },
    role: {
      head: "// current role",
      title: "Сейчас",
      company: "Инфосистемы Джет",
      position: "DevOps Expert Engineer",
      since: "окт. 2023",
      project: "Jet Detective",
      project_desc: "антифрод-платформа для банков, ритейла и промышленности",
      bullets: [
        "единственный DevOps на продукте",
        "CI/CD, мониторинг, безопасность, инфраструктура — всё на мне",
        "160+ ВМ в vSphere, 5 типов ОС, полный lifecycle через JD-Gateway",
        "Jenkins pipeline'ы с параллельными сборками и динамическими воркерами",
        "Prometheus + Grafana + Thanos, OpenSearch + Logstash — построено с нуля",
      ],
    },
    work: {
      head: "// selected work",
      title: "Избранные кейсы",
      sub: "Формат: задача → что сделал → что изменилось → чему научился. Разверни карточку.",
      items: [
        {
          id: "jd-gateway",
          tag: "infra",
          t: "JD-Gateway",
          sub: "единая точка правды для 160+ ВМ",
          meta: "Python · vSphere API · REST · Ansible · Prometheus",
          task: "На Jet Detective 160+ ВМ на тестовых стендах. Информация размазана по Confluence, головам инженеров и vSphere-консолям. Никто не знает, какие ВМ живы, кому принадлежат, когда истекает TTL.",
          did: "Разработал JD-Gateway на Python — веб-приложение с REST API, единственный источник правды. Интеграция с vSphere для полного lifecycle: создание, клонирование, удаление, питание, сеть, DNS. Dynamic inventory для Ansible и service discovery для Prometheus. TTL с email-напоминаниями. Web UI для команды.",
          changed: "Вместо ручной работы в vSphere UI — API-вызов или клик. Вместо «спроси Макса» — self-service. Ansible и Prometheus сами подхватывают новые хосты. TTL не дают стендам превращаться в зомби.",
          learned: "«Единая точка правды» — это не архитектурный паттерн, а культурное решение. Техника — 30%, остальное — убеждение и удобство.",
        },
        {
          id: "monitoring",
          tag: "observability",
          t: "Monitoring с нуля",
          sub: "для антифрод-платформы",
          meta: "Prometheus · Grafana · Thanos · OpenSearch · Logstash",
          task: "Jet Detective — продукт без мониторинга. Проблемы обнаруживались, когда кто-то жаловался или падал стенд. Нет метрик, нет алертов, нет истории.",
          did: "Построил полный стек: Prometheus для сбора, Grafana для визуализации, Thanos для долгосрочного хранения. Настроил алертинг с гибкой системой уведомлений. Добавил OpenSearch + Logstash для централизованных логов.",
          changed: "Проблемы видны до того, как кто-то пожалуется. Дашборды стали основным инструментом диагностики для всей команды. История метрик позволяет анализировать тренды и планировать ресурсы.",
          learned: "Мониторинг — это не «поставить Prometheus». Это дашборд, который конкретный человек открывает каждое утро. Если он не отвечает на вопрос «всё ли ок?» за 5 секунд — он бесполезен.",
        },
        {
          id: "jenkins",
          tag: "ci/cd",
          t: "Jenkins как основа CI/CD",
          sub: "enterprise-проект с многими ОС и компонентами",
          meta: "Jenkins · Groovy · Active Choice · OWASP · GitLab",
          task: "Сложный продукт, много компонентов, несколько ОС, куча стендов. Нужен CI/CD, который собирает, деплоит и тестирует всё это надёжно и быстро.",
          did: "Комплексные Jenkins pipeline'ы, параллельные сборки, динамическое создание воркеров в vSphere. Active Choice UI, чтобы команда собирала без чтения документации. Автотесты в PR pipeline. OWASP Dependency Check. Миграция Bitbucket → GitLab с сохранением интеграций.",
          changed: "Команда деплоит сама — без очереди к DevOps. PR не мержится без тестов. Зависимости проверяются автоматически. Сборки быстрее за счёт параллелизма.",
          learned: "Jenkins — мощный, но опасный. Без дисциплины pipeline'ы превращаются в нечитаемые Groovy-скрипты. Если что-то падает — это повод разобраться, а не обойти.",
        },
        {
          id: "mongo-egrn",
          tag: "ops",
          t: "MongoDB на проде ЕГРН",
          sub: "обновление с нулевой потерей данных",
          meta: "Ansible · MongoDB · госсистема",
          task: "Обновить MongoDB на продуктиве ЕГРН — одного из крупнейших государственных IT-проектов. Даунтайм критичен, данные терять нельзя, откат должен быть возможен.",
          did: "Разработал Ansible-плейбуки. Поднял продлайк-стенд и прогнал полный цикл миграции. Отладил до полной воспроизводимости. Провёл обновление на продуктиве.",
          changed: "Успешная миграция без потери данных и с минимальным даунтаймом.",
          learned: "На проде не бывает «попробуем». Каждый шаг — проверен на стенде, максимально похожем на прод. Плейбуки — это не скрипты, а документация, которая ещё и исполняется.",
        },
      ],
      featured: {
        id: "llm-zoo",
        badge: "featured",
        tag: "experiment",
        t: "Полтора месяца в LLM-зоопарке",
        sub: "299 часов · 16 агентов · оставил 3",
        meta: "OpenClaw · Claude Code · Codex · Gemini · Hermes · Ollama",
        task: "Понять, можно ли с помощью LLM-агентов реально снять когнитивную нагрузку — не в теории, а в ежедневной инженерной работе. Не «попробовать ChatGPT», а построить рабочую экосистему.",
        did: "299 часов за полтора месяца. Собрал экосистему из 16 агентов на двух Mac mini. Попробовал оркестрацию (OpenClaw), Claude Code, Codex, Gemini, Hermes, локальные модели (Gemma, Qwen), системы памяти (Honcho, ollama-bge-m3), управляющие слои (Multica, Paperclip).",
        timeline: {
          tried: ["OpenClaw", "Claude Code", "Codex", "Gemini", "Hermes", "Gemma", "Qwen", "Honcho", "Multica", "Paperclip", "ollama-bge-m3"],
          dropped: [
            { t: "16 параллельных агентов", d: "зашкаливающая когнитивная нагрузка, обратный эффект" },
            { t: "локальные модели на 16GB", d: "слишком слабы для реальной пользы" },
            { t: "Multica / Paperclip / Honcho", d: "оверинжиниринг, не интегрировались в рабочий процесс" },
          ],
          kept: [
            { t: "Claude Code", d: "для кода и файлов. «После правок НЕ хочется всё переписать»" },
            { t: "Клоя / OpenClaw", d: "персональный агент с памятью в Telegram" },
            { t: "Hermes", d: "для сложных задач, требующих глубокого анализа" },
          ],
        },
        learned: "Главная ловушка LLM — «когда у тебя молоток, всё вокруг гвозди». 16 агентов давали эндорфины, но не результат. Путь от усложнения к упрощению — тот же принцип, что и в DevOps: сначала порядок, потом автоматизация.",
        link: { label: "подробный разбор →", href: "https://log.artfaal.ru/posts/llm-zoo/" },
      },
    },
    principles: {
      head: "// principles",
      title: "Принципы",
      sub: "Как я подхожу к работе. Не манифест — то, что себя окупило.",
      items: [
        { n: "01", t: "Сначала порядок, потом автоматизация", d: "Автоматизировать хаос — значит получить автоматизированный хаос." },
        { n: "02", t: "Backup перед рискованными изменениями", d: "Всегда. Без исключений. Даже если «точно ничего не сломается»." },
        { n: "03", t: "Инструмент упрощает жизнь, а не строит религию", d: "Если тул требует полставки на поддержку — это не инструмент, это проект." },
        { n: "04", t: "Живое важнее стерильного", d: "Работающая система с небольшим техдолгом лучше идеальной архитектуры, которую никто не довёл до прода." },
        { n: "05", t: "Документация — часть работы", d: "Если это не записано — этого не существует. Через полгода ты сам не вспомнишь, почему так сделал." },
        { n: "06", t: "set -e, никаких скипов", d: "Если что-то падает — разберись, а не обойди." },
      ],
    },
    digging: {
      head: "// now digging",
      title: "Сейчас копаю",
      items: [
        { t: "LLM и оркестрация агентов", d: "~300 часов на OpenClaw и агентные фреймворки. Ищу способы реально снять когнитивную нагрузку." },
        { t: "LLM в production DevOps", d: "Как перенести опыт из личных экспериментов в рабочие процессы." },
        { t: "Снижение когнитивной нагрузки", d: "Автоматизация не только рутины, но и принятия решений." },
      ],
    },
    human: {
      head: "// off-hours",
      title: "По-человечески",
      sub: "То, что объясняет характер лучше любого резюме.",
      cards: [
        { t: "Cosmere",   tag: "книги",    d: "Брендон Сандерсон — ван лав. Интересно не «магия», а то, как автор держит правила мира.", img: "books" },
        { t: "Варфоломей", tag: "мотоцикл", d: "Как способ прочистить голову и переключиться. Имя дано не в шутку — это напарник, не транспорт.", img: "moto" },
        { t: "Пумба",     tag: "3D / CAD", d: "3D-принтер. Проектирую маленькие прикладные штуки для дома — кастомная подставка для книги? почему бы и нет.", img: "printer" },
        { t: "Жим лёжа",  tag: "спорт",    d: "Три года регулярно в зале. Второй разряд на соревнованиях. В планах — до мастера спорта.", img: "gym", highlight: "2-й разряд" },
        { t: "Аниме, игры", tag: "жизнь",  d: "Способ переключиться после тяжёлого дня. На игры всё меньше времени, но слежу и стараюсь находить.", img: "life" },
      ],
    },
    stack: {
      head: "// stack",
      title: "Стек",
      sub: "Core — ежедневно. Extended — регулярно. Past — был опыт, сейчас не активно.",
      groups: [
        { k: "core",     items: ["Jenkins","GitLab CI","Ansible","Docker","Prometheus","Grafana","HashiCorp Vault","VMware vSphere","Linux","PostgreSQL"] },
        { k: "extended", items: ["Thanos","Packer","OpenSearch","Logstash","Kafka","Keycloak","Nginx","Kubernetes","Terraform","Go","Python","Bash","Groovy","MinIO/S3","Apache Superset","Git","govc"] },
        { k: "past",     items: ["Flask","MongoDB","HTML/JS/CSS","DigitalOcean","Ruby","Java","SonarQube"] },
      ],
    },
    writing: {
      head: "// writing",
      title: "Заметки",
      sub: "Пишу не «контент», а живые заметки о технике, жизни и том, что зацепило. Формат — дамп сознания, без редактуры «под аудиторию».",
      links: [
        { label: "Telegram-канал", handle: "@artfaal_log", href: "https://t.me/artfaal_log" },
        { label: "Лонгриды",       handle: "log.artfaal.ru", href: "https://log.artfaal.ru" },
      ],
    },
    contacts: {
      head: "// contact",
      title: "Связаться",
      sub: "Лучше всего — Telegram. Остальное тоже работает.",
      links: [
        { label: "Telegram", handle: "@artfaal", href: "https://t.me/artfaal", key: "tg" },
        { label: "Блог",     handle: "@artfaal_log", href: "https://t.me/artfaal_log", key: "blog" },
        { label: "Email",    handle: "sys.dll@gmail.com", href: "mailto:sys.dll@gmail.com", key: "mail" },
        { label: "GitHub",   handle: "artfaal", href: "https://github.com/artfaal", key: "gh" },
        { label: "LinkedIn", handle: "maksim-solovev", href: "https://www.linkedin.com/in/maksim-solovev/", key: "in" },
      ],
    },
    footer: { built: "собрано вручную", year: "2026", sig: "// end of file" },
    // Status labels for the live MSK-time badge.
    status: {
      working:  "в работе",
      online:   "на связи",
      sleeping: "сплю",
      chilling: "выходной",
    },
    // Units for the live counters; pluralisation handled in counter.
    units: {
      y: ["год","года","лет"],
      mo: ["месяц","месяца","месяцев"],
      d: ["день","дня","дней"],
      h: ["час","часа","часов"],
      m: ["минуту","минуты","минут"],
      s: ["секунду","секунды","секунд"],
    },
  },

  en: {
    meta: {
      title: "Maksim Solovev — DevOps",
      locale: "en_US",
      handle: "artfaal",
      host: "solovev.dev",
      shell: "zsh",
      tz_label: "MSK",
    },
    nav: {
      mode_label: "mode",
      mode_work: "work",
      mode_human: "human",
      lang_label: "lang",
      cv: "download CV",
    },
    hero: {
      name: "Maksim Solovev",
      role: "DevOps Expert Engineer",
      prompt_lines: ["whoami", "cat ~/about.md"],
      tagline: [
        "I bring order to messy systems and automate the grind",
        "so people have energy left for a life.",
      ],
      sub: "Currently digging into LLM tooling — the kind that actually moves work, not the kind that spawns another zoo.",
      cta_primary: "get in touch",
      cta_secondary: "github",
      anchors: [
        { k: "in IT",         mode: "live-it",     suffix: "" },
        { k: "in DevOps",     mode: "live-devops", suffix: "" },
        { k: "VMs in prod",   mode: "static",      v: "160+" },
        { k: "tools built",   mode: "static",      v: "30+" },
        { k: "hrs in LLM zoo", mode: "static",     v: "299" },
      ],
      portrait_hint: "hover",
    },
    identity: {
      head: "// identity",
      title: "Who I am, in one paragraph",
      body: [
        "13 years in IT — from the only sysadmin at a small company to DevOps expert at Infosystems Jet. Currently — the only DevOps on Jet Detective, an anti-fraud platform for banks and retail. I own everything: from CI/CD and monitoring to 160+ VMs.",
        "Went from team lead back to expert — deliberately. I can lead a team, but I value deep engineering work more: figure it out, fix it, automate it, document it.",
      ],
      trajectory: [
        { t: "sysadmin",    y: "2013" },
        { t: "web dev",     y: "2015" },
        { t: "devops lead", y: "2019" },
        { t: "devops expert", y: "2023", current: true },
      ],
    },
    value: {
      head: "// what i do",
      title: "What I'm useful for",
      items: [
        { k: "01", t: "Turn chaos into shape",           d: "I take tangled processes and reshape them into something legible and reproducible. No cosmetics — structural." },
        { k: "02", t: "Automate without cults",          d: "Not because it's trendy — because toil eats attention. Overengineering is as much the enemy as manual labour." },
        { k: "03", t: "Hold complexity solo",            d: "Infra, debugging, orchestration. Working without a crowd is a skill — I've been sharpening it for years." },
        { k: "04", t: "Tool vs. demo",                   d: "I see fast where real utility lives and where it's a pretty wrapper. I don't let an AI-tool zoo grow unchecked." },
        { k: "05", t: "Bridge: infra ↔ AI tooling",      d: "I study LLM agents in depth and how they fit into engineering workflows. I help teams stitch infra and modern AI together without pain." },
        { k: "06", t: "No keeper of secret knowledge",   d: "Documentation, transparency, self-documenting systems. So you're not the single point of failure." },
      ],
    },
    role: {
      head: "// current role",
      title: "Right now",
      company: "Infosystems Jet",
      position: "DevOps Expert Engineer",
      since: "Oct 2023",
      project: "Jet Detective",
      project_desc: "anti-fraud platform for banks, retail and industry",
      bullets: [
        "only DevOps on the product",
        "CI/CD, monitoring, security, infrastructure — all on me",
        "160+ VMs in vSphere, 5 OS families, full lifecycle via JD-Gateway",
        "Jenkins pipelines with parallel builds and dynamic workers",
        "Prometheus + Grafana + Thanos, OpenSearch + Logstash — built from scratch",
      ],
    },
    work: {
      head: "// selected work",
      title: "Selected cases",
      sub: "Format: task → what I did → what changed → what I learned. Expand a card to read.",
      items: [
        {
          id: "jd-gateway",
          tag: "infra",
          t: "JD-Gateway",
          sub: "single source of truth for 160+ VMs",
          meta: "Python · vSphere API · REST · Ansible · Prometheus",
          task: "Jet Detective had 160+ VMs on test stands. Info was smeared across Confluence tables, engineers' heads, and vSphere consoles. Nobody knew which VMs were alive, who owned them, when TTL expired.",
          did: "Built JD-Gateway in Python — a web app with REST API, the single source of truth. Full lifecycle via vSphere: create, clone, delete, power, network, DNS. Dynamic inventory for Ansible and service discovery for Prometheus. TTL with email reminders. Web UI for the team.",
          changed: "Instead of manual vSphere work — API call or click. Instead of “ask Max” — self-service. Ansible and Prometheus auto-pick up new hosts. TTLs stop stands from turning into zombies.",
          learned: "“Single source of truth” isn't an architecture pattern, it's a cultural decision. The tech is 30% — the rest is persuasion and ergonomics.",
        },
        {
          id: "monitoring",
          tag: "observability",
          t: "Monitoring from scratch",
          sub: "for the anti-fraud platform",
          meta: "Prometheus · Grafana · Thanos · OpenSearch · Logstash",
          task: "Jet Detective had no monitoring. Problems were found when someone complained or a stand went down. No metrics, no alerts, no history.",
          did: "Full stack: Prometheus for collection, Grafana for dashboards, Thanos for long-term storage. Alerting with a flexible notification system. OpenSearch + Logstash for centralised logs.",
          changed: "Problems are visible before anyone complains. Dashboards became the primary diagnostic tool for the whole team. Metric history lets us spot trends and plan capacity.",
          learned: "Monitoring isn't “install Prometheus”. It's a dashboard a specific person opens every morning. If it doesn't answer “is everything OK?” in 5 seconds, it's useless.",
        },
        {
          id: "jenkins",
          tag: "ci/cd",
          t: "Jenkins as CI/CD backbone",
          sub: "enterprise product, many OSes and components",
          meta: "Jenkins · Groovy · Active Choice · OWASP · GitLab",
          task: "Complex product, many components, multiple OSes, lots of stands. Need CI/CD that builds, deploys and tests all of it reliably and fast.",
          did: "Comprehensive Jenkins pipelines, parallel builds, dynamic vSphere workers on demand. Active Choice UI so the team deploys without reading docs. Autotests on PR. OWASP Dependency Check. Bitbucket → GitLab migration preserving all integrations.",
          changed: "Team deploys itself — no queue at DevOps. PRs don't merge without tests. Dependencies are checked automatically. Builds got faster via parallelism.",
          learned: "Jenkins is powerful but dangerous. Without discipline, pipelines become unreadable Groovy. If something fails, the answer is to dig in, not bypass.",
        },
        {
          id: "mongo-egrn",
          tag: "ops",
          t: "MongoDB upgrade on EGRN prod",
          sub: "zero data loss on a national system",
          meta: "Ansible · MongoDB · gov. IT",
          task: "Upgrade MongoDB in production on EGRN — one of the largest government IT projects. Downtime critical, no data loss allowed, rollback mandatory.",
          did: "Ansible playbooks. Spun up a prod-like stand and ran the full migration cycle. Polished scripts until fully reproducible. Executed the upgrade on prod.",
          changed: "Successful migration, zero data loss, minimal downtime.",
          learned: "Prod has no “let's try”. Every step rehearsed on a stand that matches prod as closely as possible. Playbooks aren't scripts — they're documentation that also runs.",
        },
      ],
      featured: {
        id: "llm-zoo",
        badge: "featured",
        tag: "experiment",
        t: "Six weeks inside the LLM zoo",
        sub: "299 hours · 16 agents · kept 3",
        meta: "OpenClaw · Claude Code · Codex · Gemini · Hermes · Ollama",
        task: "Figure out whether LLM agents can actually offload cognitive work — not in theory, but in daily engineering. Not “try ChatGPT”, but build a working ecosystem.",
        did: "299 hours over six weeks. An ecosystem of 16 agents on two Mac minis. Tried orchestration (OpenClaw), Claude Code, Codex, Gemini, Hermes, local models (Gemma, Qwen), memory systems (Honcho, ollama-bge-m3), control layers (Multica, Paperclip).",
        timeline: {
          tried: ["OpenClaw","Claude Code","Codex","Gemini","Hermes","Gemma","Qwen","Honcho","Multica","Paperclip","ollama-bge-m3"],
          dropped: [
            { t: "16 parallel agents", d: "cognitive load off the charts, opposite effect" },
            { t: "local models on 16GB", d: "too weak for real utility" },
            { t: "Multica / Paperclip / Honcho", d: "overengineered, never integrated into the workflow" },
          ],
          kept: [
            { t: "Claude Code", d: "for code and files. “After its edits you don't want to rewrite everything”" },
            { t: "Kloya / OpenClaw", d: "personal agent with memory in Telegram" },
            { t: "Hermes", d: "for hard tasks requiring deep analysis" },
          ],
        },
        learned: "The LLM trap: when you have a hammer, everything looks like a nail. 16 agents felt great, delivered little. From complexity to simplicity — same rule as DevOps: order first, automation second.",
        link: { label: "full write-up →", href: "https://log.artfaal.ru/posts/llm-zoo/" },
      },
    },
    principles: {
      head: "// principles",
      title: "Principles",
      sub: "How I work. Not a manifesto — just what's paid off.",
      items: [
        { n: "01", t: "Order first, automation second", d: "Automating chaos gives you automated chaos." },
        { n: "02", t: "Back up before risky moves",     d: "Always. No exceptions. Even when “nothing can possibly break”." },
        { n: "03", t: "A tool simplifies life, not starts a religion", d: "If a tool needs half a headcount to maintain — that's not a tool, it's a project." },
        { n: "04", t: "Alive beats sterile",            d: "A working system with a bit of tech debt beats a perfect architecture nobody shipped." },
        { n: "05", t: "Docs are part of the work",      d: "If it isn't written down, it doesn't exist. In six months you won't remember why you did it this way." },
        { n: "06", t: "set -e, no skips",               d: "If something fails — dig in, don't bypass." },
      ],
    },
    digging: {
      head: "// now digging",
      title: "Currently digging",
      items: [
        { t: "LLM and agent orchestration", d: "~300 hours on OpenClaw and agent frameworks. Looking for real ways to offload cognitive work." },
        { t: "LLM in production DevOps",    d: "How to carry the personal experiments into real work." },
        { t: "Lower cognitive load",        d: "Automating not just toil, but decision-making." },
      ],
    },
    human: {
      head: "// off-hours",
      title: "The human layer",
      sub: "The stuff that explains the character better than any résumé.",
      cards: [
        { t: "Cosmere",     tag: "books",    d: "Brandon Sanderson, all in. The interesting bit isn't the “magic” — it's how he holds a world's rules.", img: "books" },
        { t: "Bartholomew", tag: "moto",     d: "The motorcycle. A way to clear the head. The name isn't a joke — he's a partner, not a vehicle.", img: "moto" },
        { t: "Pumba",       tag: "3D / CAD", d: "The 3D printer. I design small applied things for home — custom e-reader stand? why not.", img: "printer" },
        { t: "Bench press", tag: "gym",      d: "Three years at the gym. 2nd-rank rating on competition. Aiming at Master of Sport eventually.", img: "gym", highlight: "rank 2" },
        { t: "Anime, games", tag: "life",    d: "A way to switch off after a hard day. Less time for games now, but I still follow and make time.", img: "life" },
      ],
    },
    stack: {
      head: "// stack",
      title: "Stack",
      sub: "Core — daily. Extended — regularly. Past — had hands on, not active now.",
      groups: [
        { k: "core",     items: ["Jenkins","GitLab CI","Ansible","Docker","Prometheus","Grafana","HashiCorp Vault","VMware vSphere","Linux","PostgreSQL"] },
        { k: "extended", items: ["Thanos","Packer","OpenSearch","Logstash","Kafka","Keycloak","Nginx","Kubernetes","Terraform","Go","Python","Bash","Groovy","MinIO/S3","Apache Superset","Git","govc"] },
        { k: "past",     items: ["Flask","MongoDB","HTML/JS/CSS","DigitalOcean","Ruby","Java","SonarQube"] },
      ],
    },
    writing: {
      head: "// writing",
      title: "Notes",
      sub: "Not “content” — living notes on tech, life, and whatever actually stuck. Format: brain dump, no audience-tuned editing.",
      links: [
        { label: "Telegram channel", handle: "@artfaal_log", href: "https://t.me/artfaal_log" },
        { label: "Long-form",        handle: "log.artfaal.ru", href: "https://log.artfaal.ru" },
      ],
    },
    contacts: {
      head: "// contact",
      title: "Say hi",
      sub: "Telegram works best. The rest works too.",
      links: [
        { label: "Telegram", handle: "@artfaal", href: "https://t.me/artfaal", key: "tg" },
        { label: "Blog",     handle: "@artfaal_log", href: "https://t.me/artfaal_log", key: "blog" },
        { label: "Email",    handle: "sys.dll@gmail.com", href: "mailto:sys.dll@gmail.com", key: "mail" },
        { label: "GitHub",   handle: "artfaal", href: "https://github.com/artfaal", key: "gh" },
        { label: "LinkedIn", handle: "maksim-solovev", href: "https://www.linkedin.com/in/maksim-solovev/", key: "in" },
      ],
    },
    footer: { built: "hand-assembled", year: "2026", sig: "// end of file" },
    status: {
      working:  "working",
      online:   "online",
      sleeping: "asleep",
      chilling: "off the clock",
    },
    units: {
      y: ["year","years","years"],
      mo: ["month","months","months"],
      d: ["day","days","days"],
      h: ["hour","hours","hours"],
      m: ["minute","minutes","minutes"],
      s: ["second","seconds","seconds"],
    },
  },
};
